name: Assign card to user

on:
  project_card:
    types: ["moved"]

jobs:
  AssignCardToSender_job:
    runs-on: ubuntu-latest
    if: |
        #github.event.changes.column_id.from == 123456       # FIXME: Replace with "To do" column ID
        github.event.project_card.content_url != null
    steps:
      - uses: sonarsource/gh-action-lt-backlog/AssignCardToSender@v1
        with:
          github-token: ${{secrets.PERSONAL_TOKEN_TEST}}
