name: Assign card to user

on:
  project_card:
    types: ["moved"]

jobs:
  AssignCardToSender_job:
    runs-on: ubuntu-latest
    steps:
      - uses: sonarsource/gh-action-lt-backlog/AssignCardToSender@v1
        with:
          github-token: ${{secrets.PERSONAL_TOKEN_TEST}}
